collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6541218
color:
  saturation: 0.7102748
  brandStrength: 0.7258064
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#A6AF76'
    - '#DCDBA5'
    - '#A98B45'
    - '#755C1A'
  rhythmicContrast: 1
layout_spectrum: 1
name: Glazed Gourmet
